// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://abtfwlqfrfwygidphkfd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFidGZ3bHFmcmZ3eWdpZHBoa2ZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3ODk1NjIsImV4cCI6MjA2MDM2NTU2Mn0.XbliEkNmjlcGU-i80MHHZAe4n21deFQglCch51hbBCY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);